### PR TITLE
Added the ability to copy a many-to-many relationship with pivot attributes

### PR DESCRIPTION
**Pull request by korridor**
I also added a test for the timestamps in the article model.

### CODE REVIEW

**Comment by brysem** [comment]
Is this repository dead, @weotch?

**Comment by brysem** [comment]
Is this repository dead, @weotch?

**Comment by brysem** [comment]
Is this repository dead, @weotch?

**Comment by weotch** [comment]
@brysem I'm not actively working on it but, sorry, I did miss this PR coming in.

**Comment by weotch** [comment]
Thank you @korridor!

**Comment by brysem** [comment]
Thank you @korridor and @weotch!

**Pull request merged**
