### PR TITLE
Laravel 7 support

### PR DESCRIPTION
**Pull request by fridzema**

### CODE REVIEW

**Comment by denisdulici** [comment]
@weotch any chance to release a new version?

**Comment by denisdulici** [comment]
This is the only package we're waiting to upgrade to Laravel 7 so @weotch your push is appreciated.

**Comment by weotch** [comment]
Ok, just released 3.6.0, sorry for the delay.  Also, if anyone wants to be added as a maintainer, I'll add you 👍

**Comment by denisdulici** [comment]
Thanks @weotch for the release. Our @akaunting software strongly depends on your package so feel free to count me in, I would be more than happy to contribute.

**Comment by weotch** [comment]
Awesome!  Adding you now.

**Pull request merged**
